{{ if .Values.enableCertManager }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: serving-cert
spec:
  dnsNames:
  - cert-utils-operator-webhook-service.{{ .Release.Namespace }}.svc
  - cert-utils-operator-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: webhook-server-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: metrics-serving-cert
spec:
  dnsNames:
  - cert-utils-operator-controller-manager-metrics-service.{{ .Release.Namespace }}.svc
  - cert-utils-operator-controller-manager-metrics-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: cert-utils-operator-certs  
{{ end }}
