apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-utils-operator
  namespace: cert-utils-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cert-utils-operator
  template:
    metadata:
      labels:
        name: cert-utils-operator
    spec:
      serviceAccountName: cert-utils-operator
      containers:
        - name: cert-utils-operator
          image: quay.io/redhat-cop/cert-utils-operator:v0.1.0
          command:
          - cert-utils-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "cert-utils-operator"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace              