apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-utils-operator
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cert-utils-operator
  template:
    metadata:
      labels:
        name: cert-utils-operator
{{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 8 }}
{{- end }}
{{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
      {{- end }}
    spec:
      serviceAccountName: cert-utils-operator
      containers:
        - name: cert-utils-operator
          image: quay.io/redhat-cop/cert-utils-operator:{{ .Values.image_tag }}
          command:
          - cert-utils-operator
          {{- if .Values.args.jsonLog }}
          - --zap-encoder json
          {{- end }}
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "cert-utils-operator"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
